---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common
  namespace: common
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.hello-kubernetes: semver:~3.1
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: hello-kubernetes
      containers:
      - image: stefanprodan/podinfo:3.1.0
        name: hello-kubernetes
