---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common
  namespace: prod-common
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.hello-kubernetes: semver:~3.1
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: hello-kubernetes
      containers:
      - image: stefanprodan/podinfo
        name: hello-kubernetes
