---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/tag.hello-kubernetes: semver:~3.2
  name: common
  namespace: prod-common
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: hello-kubernetes
      containers:
      - image: stefanprodan/podinfo:3.2.3
        name: hello-kubernetes
