---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common
  namespace: prod-common
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.hello-kubernetes: semver:~3.2
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: hello-kubernetes
      containers:
      - image: stefanprodan/podinfo
        name: hello-kubernetes
