---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common
  namespace: common
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.hello-kubernetes: semver:~2.0
spec:
  template:
    spec:
      containers:
      - name: hello-kubernetes # (1)
        image: stefanprodan/podinfo:1.4.2
        env:
        - name: MESSAGE
          value: Hello Kubernetes! - common prod
