---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common
  namespace: common
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.testprod: semver:~1
spec:
  template:
    spec:
      containers:
      - name: testprod
        image: stefanprodan/podinfo
        env:
        - name: MESSAGE
          value: Hello Kubernetes! - common prod
