---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common
  namespace: common
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.hello-kubernetes: semver:~2.0
    fluxcd.io/tag.podinfod: semver:~3.1
spec:
  template:
    spec:
      containers:
      - name: hello-kubernetes # (1)
        image: stefanprodan/podinfo:1.4.2
        env:
        - name: MESSAGE
          value: Hello Kubernetes! - common prod
      - name: podinfod
        image: stefanprodan/podinfo:3.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9898
          name: http
        command:
        - ./podinfo
        - --port=9898
