---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common
  namespace: common
  annotations:
    fluxcd.io/automated: "true"
    #fluxcd.io/tag.hello-kubernetes: semver:~1
spec:
  template:
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        env:
        - name: MESSAGE
          value: Hello Kubernetes! - common prod
